# Polars Exercises 03 — Filtering & Sorting

Filtering rows is the Polars version of Excel's *quick filter* and pandas' boolean masks. We keep only the rows we care about with `filter()`, then put them in order with `sort()`. Master combining conditions with `&` (and), `|` (or), `~` (not) — it is the heart of every WHERE clause in our pipelines.

**Data file:** `data/orders.csv`

---

> **Solutions version** — try it yourself first from `Exercises.ipynb`.

### 1. Import Polars as `pl` and read `data/orders.csv` into `orders`.

In [1]:
import polars as pl

orders = pl.read_csv("data/orders.csv")
orders.head()

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 2. Keep only the rows where `status` is `"completed"`.

In [2]:
orders.filter(pl.col("status") == "completed")

shape: (820, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000993 ┆ CUST-0124 ┆ 2023-01-0 ┆ Europe    ┆ … ┆ 16.73     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000994 ┆ CUST-0045 ┆ 2023-01-2 ┆ Europe    ┆ … ┆ 4.58      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000995 ┆ CUST-0095 ┆ 2023-07-0 ┆ Asia      ┆ … ┆ 7.49      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 3. Keep only orders with `quantity` greater than 20.

In [3]:
orders.filter(pl.col("quantity") > 20)

shape: (469, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000006 ┆ CUST-0032 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 19.72     ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 9         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000012 ┆ CUST-0113 ┆ 2023-12-2 ┆ North     ┆ … ┆ 2.82      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000014 ┆ CUST-0159 ┆ 2023-02-0 ┆ Europe    ┆ … ┆ 21.08     ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000021 ┆ CUST-0190 ┆ 2023-07-0 ┆ Latin     ┆ … ┆ 9.85      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000993 ┆ CUST-0124 ┆ 2023-01-0 ┆ Europe    ┆ … ┆ 16.73     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000994 ┆ CUST-0045 ┆ 2023-01-2 ┆ Europe    ┆ … ┆ 4.58      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000995 ┆ CUST-0095 ┆ 2023-07-0 ┆ Asia      ┆ … ┆ 7.49      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 4. Keep online orders **from Europe** (`region == "Europe"` **and** `channel == "online"`). Remember the parentheses around each condition.

In [4]:
orders.filter((pl.col("region") == "Europe") & (pl.col("channel") == "online"))

shape: (145, 12)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_date ┆ region ┆ … ┆ unit_price ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ d          ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---        ┆ str        ┆ str    ┆   ┆ f64        ┆ str     ┆ str       ┆ ---       │
│            ┆ str        ┆            ┆        ┆   ┆            ┆         ┆           ┆ str       │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪═════════╪═══════════╪═══════════╡
│ ORD-000003 ┆ CUST-0060  ┆ 2023-02-27 ┆ Europe ┆ … ┆ 7.89       ┆ online  ┆ completed ┆ BULK      │
│ ORD-000006 ┆ CUST-0032  ┆ 2023-05-09 ┆ Europe ┆ … ┆ 19.72      ┆ online  ┆ completed ┆ SPRING10  │
│ ORD-000022 ┆ CUST-0199  ┆ 2023-10-15 ┆ Europe ┆ … ┆ 16.22      ┆ online  ┆ completed ┆ null      │
│ ORD-000028 ┆ CUST-0181  ┆ 2023-11-19 ┆ Europe ┆ … ┆ 6.26       ┆ online  ┆ completed ┆ null      │
│ ORD-000037 ┆ CUST-0086  ┆ 2023-04-18 ┆ Europe ┆ … ┆ 22.71      ┆ online  ┆ completed ┆ null      │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …          ┆ …       ┆ …         ┆ …         │
│ ORD-000978 ┆ CUST-0028  ┆ 2023-04-07 ┆ Europe ┆ … ┆ 14.47      ┆ online  ┆ cancelled ┆ BULK      │
│ ORD-000985 ┆ CUST-0037  ┆ 2023-05-20 ┆ Europe ┆ … ┆ 16.41      ┆ online  ┆ completed ┆ null      │
│ ORD-000988 ┆ CUST-0196  ┆ 2023-01-22 ┆ Europe ┆ … ┆ 8.84       ┆ online  ┆ completed ┆ VIP       │
│ ORD-000993 ┆ CUST-0124  ┆ 2023-01-05 ┆ Europe ┆ … ┆ 16.73      ┆ online  ┆ completed ┆ BULK      │
│ ORD-000994 ┆ CUST-0045  ┆ 2023-01-25 ┆ Europe ┆ … ┆ 4.58       ┆ online  ┆ completed ┆ BULK      │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴─────────┴───────────┴───────────┘

### 5. Keep orders whose `category` is **either** `"pens"` or `"books"` (use `is_in`).

In [5]:
orders.filter(pl.col("category").is_in(["pens", "books"]))

shape: (322, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000006 ┆ CUST-0032 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 19.72     ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 9         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000008 ┆ CUST-0175 ┆ 2023-08-2 ┆ North     ┆ … ┆ 7.79      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 1         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000010 ┆ CUST-0057 ┆ 2023-06-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 2         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000990 ┆ CUST-0175 ┆ 2023-08-0 ┆ North     ┆ … ┆ 8.94      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 7         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000993 ┆ CUST-0124 ┆ 2023-01-0 ┆ Europe    ┆ … ┆ 16.73     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 6. Keep orders where `quantity` is **between 10 and 20** (inclusive). Use `is_between`.

In [6]:
orders.filter(pl.col("quantity").is_between(10, 20))

shape: (274, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000007 ┆ CUST-0070 ┆ 2023-05-1 ┆ North     ┆ … ┆ 6.28      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000009 ┆ CUST-0001 ┆ 2023-08-2 ┆ Asia      ┆ … ┆ 9.14      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000983 ┆ CUST-0184 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 1.28      ┆ store   ┆ completed ┆ SPRING10  │
│            ┆           ┆ 9         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000984 ┆ CUST-0079 ┆ 2023-07-2 ┆ Latin     ┆ … ┆ 6.62      ┆ store   ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000987 ┆ CUST-0191 ┆ 2023-04-0 ┆ Europe    ┆ … ┆ 16.26     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000989 ┆ CUST-0192 ┆ 2023-05-0 ┆ North     ┆ … ┆ 11.81     ┆ store   ┆ completed ┆ BULK      │
│            ┆           ┆ 3         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 7. Find all the **returns** (rows where `quantity` is negative).

In [7]:
orders.filter(pl.col("quantity") < 0)

shape: (43, 12)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬─────────┬──────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status   ┆ discount_ │
│ ---        ┆ d          ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---      ┆ code      │
│ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str      ┆ ---       │
│            ┆ str        ┆ str       ┆           ┆   ┆ f64       ┆         ┆          ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪══════════╪═══════════╡
│ ORD-000019 ┆ CUST-0173  ┆ 2023-02-0 ┆ North     ┆ … ┆ 12.03     ┆ online  ┆ returned ┆ BULK      │
│            ┆            ┆ 5         ┆ America   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000031 ┆ CUST-0095  ┆ 2023-04-0 ┆ Asia      ┆ … ┆ 1.31      ┆ store   ┆ returned ┆ null      │
│            ┆            ┆ 2         ┆ Pacific   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000050 ┆ CUST-0021  ┆ 2023-06-3 ┆ North     ┆ … ┆ 4.73      ┆ store   ┆ returned ┆ null      │
│            ┆            ┆ 0         ┆ America   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000114 ┆ CUST-0067  ┆ 2023-02-2 ┆ North     ┆ … ┆ 20.04     ┆ store   ┆ returned ┆ null      │
│            ┆            ┆ 1         ┆ America   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000115 ┆ CUST-0050  ┆ 2023-04-0 ┆ Europe    ┆ … ┆ 1.02      ┆ online  ┆ returned ┆ BULK      │
│            ┆            ┆ 7         ┆           ┆   ┆           ┆         ┆          ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …        ┆ …         │
│ ORD-000832 ┆ CUST-0014  ┆ 2023-12-0 ┆ Asia      ┆ … ┆ 4.78      ┆ online  ┆ returned ┆ null      │
│            ┆            ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000906 ┆ CUST-0020  ┆ 2023-10-0 ┆ North     ┆ … ┆ 10.59     ┆ partner ┆ returned ┆ null      │
│            ┆            ┆ 9         ┆ America   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000942 ┆ CUST-0079  ┆ 2023-06-0 ┆ Latin     ┆ … ┆ 10.9      ┆ online  ┆ returned ┆ null      │
│            ┆            ┆ 2         ┆ America   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000991 ┆ CUST-0091  ┆ 2023-03-0 ┆ Asia      ┆ … ┆ 11.02     ┆ store   ┆ returned ┆ BULK      │
│            ┆            ┆ 7         ┆ Pacific   ┆   ┆           ┆         ┆          ┆           │
│ ORD-000999 ┆ CUST-0051  ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned ┆ VIP       │
│            ┆            ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆          ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴─────────┴──────────┴───────────┘

### 8. Keep orders whose `product_name` **contains** the text `"Pen"` (use `str.contains`).

In [8]:
orders.filter(pl.col("product_name").str.contains("Pen"))

shape: (158, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000010 ┆ CUST-0057 ┆ 2023-06-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 2         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000012 ┆ CUST-0113 ┆ 2023-12-2 ┆ North     ┆ … ┆ 2.82      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000023 ┆ CUST-0118 ┆ 2023-08-0 ┆ Asia      ┆ … ┆ 1.12      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 8         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000027 ┆ CUST-0135 ┆ 2023-06-2 ┆ North     ┆ … ┆ 1.2       ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000957 ┆ CUST-0083 ┆ 2023-12-1 ┆ North     ┆ … ┆ 2.79      ┆ online  ┆ pending   ┆ VIP       │
│            ┆           ┆ 9         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000963 ┆ CUST-0193 ┆ 2023-07-0 ┆ Europe    ┆ … ┆ 2.64      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 1         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000965 ┆ CUST-0152 ┆ 2023-07-3 ┆ North     ┆ … ┆ 1.21      ┆ store   ┆ pending   ┆ null      │
│            ┆           ┆ 1         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000970 ┆ CUST-0036 ┆ 2023-07-1 ┆ Asia      ┆ … ┆ 1.12      ┆ store   ┆ completed ┆ SPRING10  │
│            ┆           ┆ 2         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 9. Keep only rows that **have** a `discount_code` (not null).

In [9]:
orders.filter(pl.col("discount_code").is_not_null())

shape: (427, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000006 ┆ CUST-0032 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 19.72     ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 9         ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000993 ┆ CUST-0124 ┆ 2023-01-0 ┆ Europe    ┆ … ┆ 16.73     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000994 ┆ CUST-0045 ┆ 2023-01-2 ┆ Europe    ┆ … ┆ 4.58      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 10. Keep only rows that are **missing** a `discount_code` (null).

In [10]:
orders.filter(pl.col("discount_code").is_null())

shape: (573, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000007 ┆ CUST-0070 ┆ 2023-05-1 ┆ North     ┆ … ┆ 6.28      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000008 ┆ CUST-0175 ┆ 2023-08-2 ┆ North     ┆ … ┆ 7.79      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 1         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000009 ┆ CUST-0001 ┆ 2023-08-2 ┆ Asia      ┆ … ┆ 9.14      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000010 ┆ CUST-0057 ┆ 2023-06-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 2         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000987 ┆ CUST-0191 ┆ 2023-04-0 ┆ Europe    ┆ … ┆ 16.26     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000992 ┆ CUST-0039 ┆ 2023-10-2 ┆ North     ┆ … ┆ 17.35     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000995 ┆ CUST-0095 ┆ 2023-07-0 ┆ Asia      ┆ … ┆ 7.49      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 11. Keep every order **except** the cancelled ones (use `~` or `!=`).

In [11]:
orders.filter(pl.col("status") != "cancelled")

shape: (946, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000995 ┆ CUST-0095 ┆ 2023-07-0 ┆ Asia      ┆ … ┆ 7.49      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 12. Sort the whole table by `unit_price`, cheapest first.

In [12]:
orders.sort("unit_price")

shape: (1_000, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000115 ┆ CUST-0050 ┆ 2023-04-0 ┆ Europe    ┆ … ┆ 1.02      ┆ online  ┆ returned  ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000638 ┆ CUST-0009 ┆ 2023-08-1 ┆ North     ┆ … ┆ 1.02      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 3         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000342 ┆ CUST-0149 ┆ 2023-04-2 ┆ Europe    ┆ … ┆ 1.03      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 1         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000546 ┆ CUST-0024 ┆ 2023-09-2 ┆ Middle    ┆ … ┆ 1.03      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 5         ┆ East &    ┆   ┆           ┆         ┆           ┆           │
│            ┆           ┆           ┆ Africa    ┆   ┆           ┆         ┆           ┆           │
│ ORD-000884 ┆ CUST-0158 ┆ 2023-06-0 ┆ Asia      ┆ … ┆ 1.04      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 8         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000586 ┆ CUST-0159 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 25.61     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000148 ┆ CUST-0170 ┆ 2023-11-1 ┆ Latin     ┆ … ┆ 25.66     ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000724 ┆ CUST-0123 ┆ 2023-04-0 ┆ North     ┆ … ┆ 25.68     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000947 ┆ CUST-0066 ┆ 2023-01-1 ┆ North     ┆ … ┆ 25.78     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000944 ┆ CUST-0148 ┆ 2023-04-0 ┆ North     ┆ … ┆ 25.98     ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 4         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 13. Sort by `quantity`, **largest first**.

In [13]:
orders.sort("quantity", descending=True)

shape: (1_000, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000022 ┆ CUST-0199 ┆ 2023-10-1 ┆ Europe    ┆ … ┆ 16.22     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000103 ┆ CUST-0046 ┆ 2023-04-2 ┆ Latin     ┆ … ┆ 20.89     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000121 ┆ CUST-0173 ┆ 2023-10-2 ┆ North     ┆ … ┆ 10.03     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000124 ┆ CUST-0031 ┆ 2023-03-0 ┆ North     ┆ … ┆ 6.05      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 3         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000201 ┆ CUST-0061 ┆ 2023-06-1 ┆ North     ┆ … ┆ 6.82      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000739 ┆ CUST-0108 ┆ 2023-11-1 ┆ Europe    ┆ … ┆ 9.58      ┆ store   ┆ returned  ┆ BULK      │
│            ┆           ┆ 8         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000759 ┆ CUST-0163 ┆ 2023-03-1 ┆ North     ┆ … ┆ 8.46      ┆ store   ┆ returned  ┆ null      │
│            ┆           ┆ 4         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000942 ┆ CUST-0079 ┆ 2023-06-0 ┆ Latin     ┆ … ┆ 10.9      ┆ online  ┆ returned  ┆ null      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000991 ┆ CUST-0091 ┆ 2023-03-0 ┆ Asia      ┆ … ┆ 11.02     ┆ store   ┆ returned  ┆ BULK      │
│            ┆           ┆ 7         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 14. Sort by `region` (A→Z), and within each region by `unit_price` (high→low).

In [14]:
orders.sort("region", "unit_price", descending=[False, True])

shape: (1_000, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000064 ┆ CUST-0011 ┆ 2023-01-1 ┆ Asia      ┆ … ┆ 25.3      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 9         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000600 ┆ CUST-0057 ┆ 2023-07-0 ┆ Asia      ┆ … ┆ 24.95     ┆ online  ┆ returned  ┆ SPRING10  │
│            ┆           ┆ 9         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000017 ┆ CUST-0127 ┆ 2023-08-1 ┆ Asia      ┆ … ┆ 24.47     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 3         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000276 ┆ CUST-0197 ┆ 2023-06-0 ┆ Asia      ┆ … ┆ 24.33     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 7         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000747 ┆ CUST-0036 ┆ 2023-05-3 ┆ Asia      ┆ … ┆ 23.97     ┆ online  ┆ completed ┆ VIP       │
│            ┆           ┆ 1         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000761 ┆ CUST-0162 ┆ 2023-05-2 ┆ North     ┆ … ┆ 1.07      ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000804 ┆ CUST-0068 ┆ 2023-02-1 ┆ North     ┆ … ┆ 1.07      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 7         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000627 ┆ CUST-0123 ┆ 2023-03-1 ┆ North     ┆ … ┆ 1.07      ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000106 ┆ CUST-0049 ┆ 2023-11-2 ┆ North     ┆ … ┆ 1.06      ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 1         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000638 ┆ CUST-0009 ┆ 2023-08-1 ┆ North     ┆ … ┆ 1.02      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 3         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 15. Show the **5 most expensive orders** (highest `unit_price`).

In [15]:
orders.top_k(5, by="unit_price")

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000944 ┆ CUST-0148 ┆ 2023-04-0 ┆ North     ┆ … ┆ 25.98     ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 4         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000947 ┆ CUST-0066 ┆ 2023-01-1 ┆ North     ┆ … ┆ 25.78     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000724 ┆ CUST-0123 ┆ 2023-04-0 ┆ North     ┆ … ┆ 25.68     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000148 ┆ CUST-0170 ┆ 2023-11-1 ┆ Latin     ┆ … ┆ 25.66     ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000586 ┆ CUST-0159 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 25.61     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 16. **How many** completed online orders from Europe have `quantity` of at least 15? (filter, then count the rows)

In [16]:
orders.filter(
    (pl.col("status") == "completed")
    & (pl.col("channel") == "online")
    & (pl.col("region") == "Europe")
    & (pl.col("quantity") >= 15)
).height

78