# Polars Exercises 02 — Selecting & Subsetting

Now that we know the data, the next everyday task is **choosing the columns we actually need** — the building block of every Foundry transform. In Polars this is done with `select()` and **expressions** (`pl.col`), not with `[[...]]` bracket lists like in pandas.


**Data file:** `data/orders.csv`

---

### 1. Import Polars as `pl`, import the selectors module as `cs`, and read `data/orders.csv` into `orders`.

In [1]:
import polars as pl
import polars.selectors as cs

orders = pl.read_csv("data/orders.csv")
orders.head()

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 2. Select only the columns `order_id`, `product_name`, `quantity`.

In [2]:
orders.select("order_id", "product_name", "quantity")

shape: (1_000, 3)
┌────────────┬─────────────────────┬──────────┐
│ order_id   ┆ product_name        ┆ quantity │
│ ---        ┆ ---                 ┆ ---      │
│ str        ┆ str                 ┆ i64      │
╞════════════╪═════════════════════╪══════════╡
│ ORD-000001 ┆ Gel Pen 12-pack     ┆ 15       │
│ ORD-000002 ┆ Cotton T-Shirt      ┆ 5        │
│ ORD-000003 ┆ Paperback Book      ┆ 16       │
│ ORD-000004 ┆ Cotton T-Shirt      ┆ 37       │
│ ORD-000005 ┆ Motivational Poster ┆ 11       │
│ …          ┆ …                   ┆ …        │
│ ORD-000996 ┆ Cookbook            ┆ 2        │
│ ORD-000997 ┆ World Map Poster    ┆ 37       │
│ ORD-000998 ┆ Sticker Sheet       ┆ 16       │
│ ORD-000999 ┆ Gel Pen 12-pack     ┆ -5       │
│ ORD-001000 ┆ Paperback Book      ┆ 34       │
└────────────┴─────────────────────┴──────────┘

### 3. Do the same selection, but this time using **expressions** (`pl.col(...)`).

In [3]:
orders.select(pl.col("order_id"), pl.col("product_name"), pl.col("quantity"))

shape: (1_000, 3)
┌────────────┬─────────────────────┬──────────┐
│ order_id   ┆ product_name        ┆ quantity │
│ ---        ┆ ---                 ┆ ---      │
│ str        ┆ str                 ┆ i64      │
╞════════════╪═════════════════════╪══════════╡
│ ORD-000001 ┆ Gel Pen 12-pack     ┆ 15       │
│ ORD-000002 ┆ Cotton T-Shirt      ┆ 5        │
│ ORD-000003 ┆ Paperback Book      ┆ 16       │
│ ORD-000004 ┆ Cotton T-Shirt      ┆ 37       │
│ ORD-000005 ┆ Motivational Poster ┆ 11       │
│ …          ┆ …                   ┆ …        │
│ ORD-000996 ┆ Cookbook            ┆ 2        │
│ ORD-000997 ┆ World Map Poster    ┆ 37       │
│ ORD-000998 ┆ Sticker Sheet       ┆ 16       │
│ ORD-000999 ┆ Gel Pen 12-pack     ┆ -5       │
│ ORD-001000 ┆ Paperback Book      ┆ 34       │
└────────────┴─────────────────────┴──────────┘

### 4. Select **all columns except** `quantity` and `unit_price`.

In [4]:
orders.select(pl.exclude("quantity", "unit_price"))

shape: (1_000, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ product_n ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ame       ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ str       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ Gel Pen   ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆ 12-pack   ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ Cotton    ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆ T-Shirt   ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ Paperback ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆ Book      ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ Cotton    ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆ T-Shirt   ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ Motivatio ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆ nal       ┆         ┆           ┆           │
│            ┆           ┆           ┆           ┆   ┆ Poster    ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ Cookbook  ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ World Map ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆ Poster    ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ Sticker   ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆ Sheet     ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ Gel Pen   ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆ 12-pack   ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ Paperback ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆ Book      ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 5. **Rename** `region` to `sales_region` and `channel` to `sales_channel`.

In [5]:
orders.rename({"region": "sales_region", "channel": "sales_channel"})

shape: (1_000, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_id  ┆ customer_ ┆ order_dat ┆ sales_reg ┆ … ┆ unit_pric ┆ sales_cha ┆ status    ┆ discount │
│ ---       ┆ id        ┆ e         ┆ ion       ┆   ┆ e         ┆ nnel      ┆ ---       ┆ _code    │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ORD-00000 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online    ┆ completed ┆ SPRING10 │
│ 1         ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online    ┆ completed ┆ BULK     │
│ 2         ┆           ┆ 2         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online    ┆ completed ┆ BULK     │
│ 3         ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online    ┆ completed ┆ BULK     │
│ 4         ┆           ┆ 6         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online    ┆ completed ┆ null     │
│ 5         ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ORD-00099 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online    ┆ cancelled ┆ null     │
│ 6         ┆           ┆ 6         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00099 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store     ┆ completed ┆ VIP      │
│ 7         ┆           ┆ 8         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00099 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online    ┆ pending   ┆ SPRING10 │
│ 8         ┆           ┆ 5         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00099 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online    ┆ returned  ┆ VIP      │
│ 9         ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00100 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner   ┆ completed ┆ null     │
│ 0         ┆           ┆ 0         ┆ America   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 6. **Drop** the `discount_code` column.

In [6]:
orders.drop("discount_code")

shape: (1_000, 11)
┌────────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬─────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_dat ┆ region    ┆ … ┆ quantity ┆ unit_pric ┆ channel ┆ status    │
│ ---        ┆ d          ┆ e         ┆ ---       ┆   ┆ ---      ┆ e         ┆ ---     ┆ ---       │
│ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ i64      ┆ ---       ┆ str     ┆ str       │
│            ┆ str        ┆ str       ┆           ┆   ┆          ┆ f64       ┆         ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171  ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 15       ┆ 2.7       ┆ online  ┆ completed │
│            ┆            ┆ 5         ┆ Pacific   ┆   ┆          ┆           ┆         ┆           │
│ ORD-000002 ┆ CUST-0049  ┆ 2023-12-0 ┆ North     ┆ … ┆ 5        ┆ 17.88     ┆ online  ┆ completed │
│            ┆            ┆ 2         ┆ America   ┆   ┆          ┆           ┆         ┆           │
│ ORD-000003 ┆ CUST-0060  ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 16       ┆ 7.89      ┆ online  ┆ completed │
│            ┆            ┆ 7         ┆           ┆   ┆          ┆           ┆         ┆           │
│ ORD-000004 ┆ CUST-0065  ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 37       ┆ 17.06     ┆ online  ┆ completed │
│            ┆            ┆ 6         ┆ America   ┆   ┆          ┆           ┆         ┆           │
│ ORD-000005 ┆ CUST-0036  ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 11       ┆ 7.26      ┆ online  ┆ completed │
│            ┆            ┆ 4         ┆ Pacific   ┆   ┆          ┆           ┆         ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …       ┆ …         │
│ ORD-000996 ┆ CUST-0132  ┆ 2023-07-0 ┆ North     ┆ … ┆ 2        ┆ 20.78     ┆ online  ┆ cancelled │
│            ┆            ┆ 6         ┆ America   ┆   ┆          ┆           ┆         ┆           │
│ ORD-000997 ┆ CUST-0190  ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 37       ┆ 9.13      ┆ store   ┆ completed │
│            ┆            ┆ 8         ┆ America   ┆   ┆          ┆           ┆         ┆           │
│ ORD-000998 ┆ CUST-0058  ┆ 2023-04-0 ┆ North     ┆ … ┆ 16       ┆ 1.4       ┆ online  ┆ pending   │
│            ┆            ┆ 5         ┆ America   ┆   ┆          ┆           ┆         ┆           │
│ ORD-000999 ┆ CUST-0051  ┆ 2023-01-2 ┆ Asia      ┆ … ┆ -5       ┆ 3.11      ┆ online  ┆ returned  │
│            ┆            ┆ 6         ┆ Pacific   ┆   ┆          ┆           ┆         ┆           │
│ ORD-001000 ┆ CUST-0147  ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 34       ┆ 8.87      ┆ partner ┆ completed │
│            ┆            ┆ 0         ┆ America   ┆   ┆          ┆           ┆         ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴─────────┴───────────┘

### 7. Select all columns, but with `quantity` and `unit_price` **first** (reorder columns).

In [7]:
orders.select("quantity", "unit_price", pl.exclude("quantity", "unit_price"))

shape: (1_000, 12)
┌──────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ quantity ┆ unit_price ┆ order_id   ┆ customer_ ┆ … ┆ product_n ┆ channel ┆ status    ┆ discount_ │
│ ---      ┆ ---        ┆ ---        ┆ id        ┆   ┆ ame       ┆ ---     ┆ ---       ┆ code      │
│ i64      ┆ f64        ┆ str        ┆ ---       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│          ┆            ┆            ┆ str       ┆   ┆ str       ┆         ┆           ┆ str       │
╞══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 15       ┆ 2.7        ┆ ORD-000001 ┆ CUST-0171 ┆ … ┆ Gel Pen   ┆ online  ┆ completed ┆ SPRING10  │
│          ┆            ┆            ┆           ┆   ┆ 12-pack   ┆         ┆           ┆           │
│ 5        ┆ 17.88      ┆ ORD-000002 ┆ CUST-0049 ┆ … ┆ Cotton    ┆ online  ┆ completed ┆ BULK      │
│          ┆            ┆            ┆           ┆   ┆ T-Shirt   ┆         ┆           ┆           │
│ 16       ┆ 7.89       ┆ ORD-000003 ┆ CUST-0060 ┆ … ┆ Paperback ┆ online  ┆ completed ┆ BULK      │
│          ┆            ┆            ┆           ┆   ┆ Book      ┆         ┆           ┆           │
│ 37       ┆ 17.06      ┆ ORD-000004 ┆ CUST-0065 ┆ … ┆ Cotton    ┆ online  ┆ completed ┆ BULK      │
│          ┆            ┆            ┆           ┆   ┆ T-Shirt   ┆         ┆           ┆           │
│ 11       ┆ 7.26       ┆ ORD-000005 ┆ CUST-0036 ┆ … ┆ Motivatio ┆ online  ┆ completed ┆ null      │
│          ┆            ┆            ┆           ┆   ┆ nal       ┆         ┆           ┆           │
│          ┆            ┆            ┆           ┆   ┆ Poster    ┆         ┆           ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ 2        ┆ 20.78      ┆ ORD-000996 ┆ CUST-0132 ┆ … ┆ Cookbook  ┆ online  ┆ cancelled ┆ null      │
│ 37       ┆ 9.13       ┆ ORD-000997 ┆ CUST-0190 ┆ … ┆ World Map ┆ store   ┆ completed ┆ VIP       │
│          ┆            ┆            ┆           ┆   ┆ Poster    ┆         ┆           ┆           │
│ 16       ┆ 1.4        ┆ ORD-000998 ┆ CUST-0058 ┆ … ┆ Sticker   ┆ online  ┆ pending   ┆ SPRING10  │
│          ┆            ┆            ┆           ┆   ┆ Sheet     ┆         ┆           ┆           │
│ -5       ┆ 3.11       ┆ ORD-000999 ┆ CUST-0051 ┆ … ┆ Gel Pen   ┆ online  ┆ returned  ┆ VIP       │
│          ┆            ┆            ┆           ┆   ┆ 12-pack   ┆         ┆           ┆           │
│ 34       ┆ 8.87       ┆ ORD-001000 ┆ CUST-0147 ┆ … ┆ Paperback ┆ partner ┆ completed ┆ null      │
│          ┆            ┆            ┆           ┆   ┆ Book      ┆         ┆           ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 8. Using **selectors**, select all the **string** columns.

In [8]:
orders.select(cs.string())

shape: (1_000, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ product_n ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ame       ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ str       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ Gel Pen   ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆ 12-pack   ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ Cotton    ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆ T-Shirt   ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ Paperback ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆ Book      ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ Cotton    ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆ T-Shirt   ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ Motivatio ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆ nal       ┆         ┆           ┆           │
│            ┆           ┆           ┆           ┆   ┆ Poster    ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ Cookbook  ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ World Map ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆ Poster    ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ Sticker   ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆ Sheet     ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ Gel Pen   ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆ 12-pack   ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ Paperback ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆ Book      ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 9. Using **selectors**, select all the **numeric** columns.

In [9]:
orders.select(cs.numeric())

shape: (1_000, 2)
┌──────────┬────────────┐
│ quantity ┆ unit_price │
│ ---      ┆ ---        │
│ i64      ┆ f64        │
╞══════════╪════════════╡
│ 15       ┆ 2.7        │
│ 5        ┆ 17.88      │
│ 16       ┆ 7.89       │
│ 37       ┆ 17.06      │
│ 11       ┆ 7.26       │
│ …        ┆ …          │
│ 2        ┆ 20.78      │
│ 37       ┆ 9.13       │
│ 16       ┆ 1.4        │
│ -5       ┆ 3.11       │
│ 34       ┆ 8.87       │
└──────────┴────────────┘

### 10. Get the `quantity` column **as a Series**.

In [10]:
orders.get_column("quantity")

shape: (1_000,)
Series: 'quantity' [i64]
[
	15
	5
	16
	37
	11
	…
	2
	37
	16
	-5
	34
]

### 11. Get a **single value**: the `unit_price` of the very first row.

In [11]:
orders.select("unit_price").item(0, 0)

2.7

### 12. Select all columns whose name **starts with `order`** (use a selector).

In [12]:
orders.select(cs.starts_with("order"))

shape: (1_000, 2)
┌────────────┬────────────┐
│ order_id   ┆ order_date │
│ ---        ┆ ---        │
│ str        ┆ str        │
╞════════════╪════════════╡
│ ORD-000001 ┆ 2023-10-25 │
│ ORD-000002 ┆ 2023-12-02 │
│ ORD-000003 ┆ 2023-02-27 │
│ ORD-000004 ┆ 2023-12-26 │
│ ORD-000005 ┆ 2023-05-24 │
│ …          ┆ …          │
│ ORD-000996 ┆ 2023-07-06 │
│ ORD-000997 ┆ 2023-04-18 │
│ ORD-000998 ┆ 2023-04-05 │
│ ORD-000999 ┆ 2023-01-26 │
│ ORD-001000 ┆ 2023-08-30 │
└────────────┴────────────┘

### 13. Select `unit_price`, but rename it to `price` in the result (use `.alias`).

In [13]:
orders.select(pl.col("unit_price").alias("price"))

shape: (1_000, 1)
┌───────┐
│ price │
│ ---   │
│ f64   │
╞═══════╡
│ 2.7   │
│ 17.88 │
│ 7.89  │
│ 17.06 │
│ 7.26  │
│ …     │
│ 20.78 │
│ 9.13  │
│ 1.4   │
│ 3.11  │
│ 8.87  │
└───────┘

### 14. Select the **first 3 columns by position** (hint: `orders.columns`).

In [14]:
orders.select(orders.columns[:3])

shape: (1_000, 3)
┌────────────┬─────────────┬────────────┐
│ order_id   ┆ customer_id ┆ order_date │
│ ---        ┆ ---         ┆ ---        │
│ str        ┆ str         ┆ str        │
╞════════════╪═════════════╪════════════╡
│ ORD-000001 ┆ CUST-0171   ┆ 2023-10-25 │
│ ORD-000002 ┆ CUST-0049   ┆ 2023-12-02 │
│ ORD-000003 ┆ CUST-0060   ┆ 2023-02-27 │
│ ORD-000004 ┆ CUST-0065   ┆ 2023-12-26 │
│ ORD-000005 ┆ CUST-0036   ┆ 2023-05-24 │
│ …          ┆ …           ┆ …          │
│ ORD-000996 ┆ CUST-0132   ┆ 2023-07-06 │
│ ORD-000997 ┆ CUST-0190   ┆ 2023-04-18 │
│ ORD-000998 ┆ CUST-0058   ┆ 2023-04-05 │
│ ORD-000999 ┆ CUST-0051   ┆ 2023-01-26 │
│ ORD-001000 ┆ CUST-0147   ┆ 2023-08-30 │
└────────────┴─────────────┴────────────┘

### 15. Find all the **distinct combinations** of `region` and `channel`.

In [15]:
orders.select("region", "channel").unique().sort("region", "channel")

shape: (15, 2)
┌──────────────────────┬─────────┐
│ region               ┆ channel │
│ ---                  ┆ ---     │
│ str                  ┆ str     │
╞══════════════════════╪═════════╡
│ Asia Pacific         ┆ online  │
│ Asia Pacific         ┆ partner │
│ Asia Pacific         ┆ store   │
│ Europe               ┆ online  │
│ Europe               ┆ partner │
│ …                    ┆ …       │
│ Middle East & Africa ┆ partner │
│ Middle East & Africa ┆ store   │
│ North America        ┆ online  │
│ North America        ┆ partner │
│ North America        ┆ store   │
└──────────────────────┴─────────┘