# Polars Exercises 04 — Creating & Transforming Columns

This is where transforms come alive. We use `with_columns()` to **add or change** columns: arithmetic (revenue = quantity × price), fixing data types (the string `order_date` → a real date), string cleaning, and conditional logic with `when/then/otherwise`. These are the exact operations we write all day long in Foundry.


**Data file:** `data/orders.csv`

---

### 1. Import Polars as `pl` and read `data/orders.csv` into `orders`.

In [1]:
import polars as pl

orders = pl.read_csv("data/orders.csv")
orders.head()

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 2. Add a new column `revenue` = `quantity` × `unit_price`.

In [2]:
orders.with_columns(revenue=pl.col("quantity") * pl.col("unit_price"))

shape: (1_000, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬───────────┬───────────┬─────────┐
│ order_id   ┆ customer_i ┆ order_date ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ revenue │
│ ---        ┆ d          ┆ ---        ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ ---     │
│ str        ┆ ---        ┆ str        ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ f64     │
│            ┆ str        ┆            ┆           ┆   ┆         ┆           ┆ str       ┆         │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═════════╡
│ ORD-000001 ┆ CUST-0171  ┆ 2023-10-25 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ 40.5    │
│            ┆            ┆            ┆ Pacific   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000002 ┆ CUST-0049  ┆ 2023-12-02 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 89.4    │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000003 ┆ CUST-0060  ┆ 2023-02-27 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 126.24  │
│ ORD-000004 ┆ CUST-0065  ┆ 2023-12-26 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 631.22  │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000005 ┆ CUST-0036  ┆ 2023-05-24 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ 79.86   │
│            ┆            ┆            ┆ Pacific   ┆   ┆         ┆           ┆           ┆         │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …       │
│ ORD-000996 ┆ CUST-0132  ┆ 2023-07-06 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ 41.56   │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000997 ┆ CUST-0190  ┆ 2023-04-18 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ 337.81  │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000998 ┆ CUST-0058  ┆ 2023-04-05 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ 22.4    │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000999 ┆ CUST-0051  ┆ 2023-01-26 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ -15.55  │
│            ┆            ┆            ┆ Pacific   ┆   ┆         ┆           ┆           ┆         │
│ ORD-001000 ┆ CUST-0147  ┆ 2023-08-30 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ 301.58  │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴───────────┴───────────┴─────────┘

### 3. Add `revenue` again, but **rounded to 2 decimals** (use `.round(2)`).

In [3]:
orders.with_columns(
    revenue=(pl.col("quantity") * pl.col("unit_price")).round(2)
)

shape: (1_000, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬───────────┬───────────┬─────────┐
│ order_id   ┆ customer_i ┆ order_date ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ revenue │
│ ---        ┆ d          ┆ ---        ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ ---     │
│ str        ┆ ---        ┆ str        ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ f64     │
│            ┆ str        ┆            ┆           ┆   ┆         ┆           ┆ str       ┆         │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═════════╡
│ ORD-000001 ┆ CUST-0171  ┆ 2023-10-25 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ 40.5    │
│            ┆            ┆            ┆ Pacific   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000002 ┆ CUST-0049  ┆ 2023-12-02 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 89.4    │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000003 ┆ CUST-0060  ┆ 2023-02-27 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 126.24  │
│ ORD-000004 ┆ CUST-0065  ┆ 2023-12-26 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 631.22  │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000005 ┆ CUST-0036  ┆ 2023-05-24 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ 79.86   │
│            ┆            ┆            ┆ Pacific   ┆   ┆         ┆           ┆           ┆         │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …       │
│ ORD-000996 ┆ CUST-0132  ┆ 2023-07-06 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ 41.56   │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000997 ┆ CUST-0190  ┆ 2023-04-18 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ 337.81  │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000998 ┆ CUST-0058  ┆ 2023-04-05 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ 22.4    │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
│ ORD-000999 ┆ CUST-0051  ┆ 2023-01-26 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ -15.55  │
│            ┆            ┆            ┆ Pacific   ┆   ┆         ┆           ┆           ┆         │
│ ORD-001000 ┆ CUST-0147  ┆ 2023-08-30 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ 301.58  │
│            ┆            ┆            ┆ America   ┆   ┆         ┆           ┆           ┆         │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴───────────┴───────────┴─────────┘

### 4. The `order_date` column is a **string**. Convert it to a real **Date** column (format `"%Y-%m-%d"`).

In [4]:
orders.with_columns(
    pl.col("order_date").str.to_date("%Y-%m-%d")
)

shape: (1_000, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ date      ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 5. From `order_date`, create a new integer column `order_month` (1–12).

In [5]:
orders.with_columns(
    order_month=pl.col("order_date").str.to_date("%Y-%m-%d").dt.month()
)

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ order_mon │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ th        │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ i8        │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ 10        │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 12        │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 2         │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 12        │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ 5         │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ 7         │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ 4         │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ 4         │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ 1         │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ 8         │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 6. Add two columns from `order_date`: `order_year` and `order_quarter`.

In [6]:
d = pl.col("order_date").str.to_date("%Y-%m-%d")
orders.with_columns(
    order_year=d.dt.year(),
    order_quarter=d.dt.quarter(),
)

shape: (1_000, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_id  ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ status    ┆ discount_ ┆ order_yea ┆ order_qu │
│ ---       ┆ id        ┆ e         ┆ ---       ┆   ┆ ---       ┆ code      ┆ r         ┆ arter    │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆           ┆ str       ┆ i32       ┆ i8       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ORD-00000 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ completed ┆ SPRING10  ┆ 2023      ┆ 4        │
│ 1         ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ completed ┆ BULK      ┆ 2023      ┆ 4        │
│ 2         ┆           ┆ 2         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ completed ┆ BULK      ┆ 2023      ┆ 1        │
│ 3         ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ completed ┆ BULK      ┆ 2023      ┆ 4        │
│ 4         ┆           ┆ 6         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00000 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ completed ┆ null      ┆ 2023      ┆ 2        │
│ 5         ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ORD-00099 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ cancelled ┆ null      ┆ 2023      ┆ 3        │
│ 6         ┆           ┆ 6         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00099 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ completed ┆ VIP       ┆ 2023      ┆ 2        │
│ 7         ┆           ┆ 8         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00099 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ pending   ┆ SPRING10  ┆ 2023      ┆ 2        │
│ 8         ┆           ┆ 5         ┆ America   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00099 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ returned  ┆ VIP       ┆ 2023      ┆ 1        │
│ 9         ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│ ORD-00100 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ completed ┆ null      ┆ 2023      ┆ 3        │
│ 0         ┆           ┆ 0         ┆ America   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 7. Add a boolean column `is_return` that is `True` when `quantity` is negative.

In [7]:
orders.with_columns(is_return=pl.col("quantity") < 0)

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ is_return │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ bool      │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ false     │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ false     │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ false     │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ false     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ false     │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ false     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ false     │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ false     │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ true      │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ false     │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 8. Add a column `order_size` using `when/then/otherwise`: `"small"` if quantity < 10, `"medium"` if 10–25, `"large"` if > 25.

In [8]:
orders.with_columns(
    order_size=pl.when(pl.col("quantity") < 10).then(pl.lit("small"))
    .when(pl.col("quantity") <= 25).then(pl.lit("medium"))
    .otherwise(pl.lit("large"))
)

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ order_siz │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ e         │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ medium    │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ small     │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ medium    │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ large     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ medium    │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ small     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ large     │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ medium    │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ small     │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ large     │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 9. Add `region_upper` = the `region` in UPPERCASE (use `str.to_uppercase`).

In [9]:
orders.with_columns(region_upper=pl.col("region").str.to_uppercase())

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ region_up │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ per       │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ ASIA      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆ PACIFIC   │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ NORTH     │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆ AMERICA   │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ EUROPE    │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ LATIN     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆ AMERICA   │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ ASIA      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆ PACIFIC   │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ NORTH     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆ AMERICA   │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ LATIN     │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆ AMERICA   │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ NORTH     │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆ AMERICA   │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ ASIA      │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆ PACIFIC   │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ LATIN     │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆ AMERICA   │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 10. Add `sku_prefix` = the **first 2 characters** of `product_sku` (use `str.slice`).

In [10]:
orders.with_columns(sku_prefix=pl.col("product_sku").str.slice(0, 2))

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ sku_prefi │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ x         │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ PB        │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ SH        │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ BK        │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ SH        │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ PT        │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ BK        │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ PT        │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ ST        │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ PB        │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ BK        │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 11. Add `channel_clean` where the value `"online"` is replaced by `"web"` (use `str.replace`).

In [11]:
orders.with_columns(
    channel_clean=pl.col("channel").str.replace("online", "web")
)

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ channel_c │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ lean      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ web       │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ web       │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ web       │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ web       │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ web       │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ web       │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ store     │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ web       │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ web       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ partner   │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 12. Add `name_length` = the number of characters in `product_name` (use `str.len_chars`).

In [12]:
orders.with_columns(name_length=pl.col("product_name").str.len_chars())

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ name_leng │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ th        │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ u32       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ 15        │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 14        │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 14        │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 14        │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ 19        │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ 8         │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ 16        │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ 13        │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ 15        │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ 14        │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 13. Fill the missing `discount_code` values with the text `"NONE"` (use `fill_null`).

In [13]:
orders.with_columns(
    discount_code=pl.col("discount_code").fill_null("NONE")
)

shape: (1_000, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ NONE      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online  ┆ cancelled ┆ NONE      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ NONE      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 14. Add **two columns at once** in a single `with_columns`: `revenue` (quantity × price) and `is_return` (quantity < 0).

In [14]:
orders.with_columns(
    revenue=pl.col("quantity") * pl.col("unit_price"),
    is_return=pl.col("quantity") < 0,
)

shape: (1_000, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ status    ┆ discount_ ┆ revenue ┆ is_return │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---       ┆ code      ┆ ---     ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ f64     ┆ bool      │
│            ┆ str       ┆ str       ┆           ┆   ┆           ┆ str       ┆         ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ completed ┆ SPRING10  ┆ 40.5    ┆ false     │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆           ┆         ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ completed ┆ BULK      ┆ 89.4    ┆ false     │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆           ┆         ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ completed ┆ BULK      ┆ 126.24  ┆ false     │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆         ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ completed ┆ BULK      ┆ 631.22  ┆ false     │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆           ┆         ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ completed ┆ null      ┆ 79.86   ┆ false     │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆           ┆         ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ cancelled ┆ null      ┆ 41.56   ┆ false     │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆           ┆         ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ completed ┆ VIP       ┆ 337.81  ┆ false     │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆           ┆         ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ pending   ┆ SPRING10  ┆ 22.4    ┆ false     │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆           ┆         ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ returned  ┆ VIP       ┆ -15.55  ┆ true      │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆           ┆         ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ completed ┆ null      ┆ 301.58  ┆ false     │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

### 15. Add `price_with_tax` = `unit_price` × 1.17, rounded to 2 decimals.

In [15]:
orders.with_columns(
    price_with_tax=(pl.col("unit_price") * 1.17).round(2)
)

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ price_wit │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ h_tax     │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ 3.16      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 20.92     │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 9.23      │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 19.96     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ 8.49      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ 24.31     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ 10.68     │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ 1.64      │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ 3.64      │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ 10.38     │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 16. Build a `segment` column by joining `region` and `channel` with `" / "` between them (use `pl.concat_str`).

In [16]:
orders.with_columns(
    segment=pl.concat_str(["region", "channel"], separator=" / ")
)

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ segment   │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ str       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ Asia      │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆ Pacific / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ North     │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆ America / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ Europe /  │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ Latin     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆ America / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ Asia      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆ Pacific / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ North     │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆ America / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ Latin     │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆ America / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ store     │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ North     │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆ America / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ Asia      │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆ Pacific / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ online    │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ Latin     │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆ America / │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ partner   │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

### 17. Add `priority` = `"high"` when `revenue` (quantity × price) is over 500, otherwise `"normal"`.

In [17]:
orders.with_columns(
    priority=pl.when(pl.col("quantity") * pl.col("unit_price") > 500)
    .then(pl.lit("high"))
    .otherwise(pl.lit("normal"))
)

shape: (1_000, 13)
┌────────────┬────────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬──────────┐
│ order_id   ┆ customer_i ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ priority │
│ ---        ┆ d          ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ ---      │
│ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ str      │
│            ┆ str        ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆          │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪══════════╡
│ ORD-000001 ┆ CUST-0171  ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ normal   │
│            ┆            ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆          │
│ ORD-000002 ┆ CUST-0049  ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ normal   │
│            ┆            ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆          │
│ ORD-000003 ┆ CUST-0060  ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ normal   │
│            ┆            ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆          │
│ ORD-000004 ┆ CUST-0065  ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ high     │
│            ┆            ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆          │
│ ORD-000005 ┆ CUST-0036  ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ normal   │
│            ┆            ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆          │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …        │
│ ORD-000996 ┆ CUST-0132  ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ normal   │
│            ┆            ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆          │
│ ORD-000997 ┆ CUST-0190  ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ normal   │
│            ┆            ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆          │
│ ORD-000998 ┆ CUST-0058  ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ normal   │
│            ┆            ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆          │
│ ORD-000999 ┆ CUST-0051  ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ normal   │
│            ┆            ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆          │
│ ORD-001000 ┆ CUST-0147  ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ normal   │
│            ┆            ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆          │
└────────────┴────────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴──────────┘

### 18. Add `abs_quantity` = the **absolute value** of `quantity` (returns become positive).

In [18]:
orders.with_columns(abs_quantity=pl.col("quantity").abs())

shape: (1_000, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ channel ┆ status    ┆ discount_ ┆ abs_quant │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ ---     ┆ ---       ┆ code      ┆ ity       │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ str     ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆         ┆           ┆ str       ┆ i64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ SPRING10  ┆ 15        │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 5         │
│            ┆           ┆ 2         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 16        │
│            ┆           ┆ 7         ┆           ┆   ┆         ┆           ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ online  ┆ completed ┆ BULK      ┆ 37        │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ online  ┆ completed ┆ null      ┆ 11        │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ online  ┆ cancelled ┆ null      ┆ 2         │
│            ┆           ┆ 6         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ store   ┆ completed ┆ VIP       ┆ 37        │
│            ┆           ┆ 8         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ online  ┆ pending   ┆ SPRING10  ┆ 16        │
│            ┆           ┆ 5         ┆ America   ┆   ┆         ┆           ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ online  ┆ returned  ┆ VIP       ┆ 5         │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆         ┆           ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ partner ┆ completed ┆ null      ┆ 34        │
│            ┆           ┆ 0         ┆ America   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘