# Polars Exercises 01 — Getting & Knowing Your Data

A raw `orders` dataset just landed in our pipeline (think of a new dataset in Palantir Foundry). Before we build *any* transform on top of it, we have to **get to know the data**: its shape, its columns, its types, and where it is dirty.

**Data file:** `data/orders.csv`

---

> **Solutions version** — try it yourself first from `Exercises.ipynb`.

### 1. Import Polars under the alias `pl`.

In [1]:
import polars as pl

### 2. Read `data/orders.csv` into a DataFrame called `orders`.

In [2]:
orders = pl.read_csv("data/orders.csv")
orders

shape: (1_000, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 3. Show the **first 10 rows**.

In [3]:
orders.head(10)

shape: (10, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000001 ┆ CUST-0171 ┆ 2023-10-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 5         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000002 ┆ CUST-0049 ┆ 2023-12-0 ┆ North     ┆ … ┆ 17.88     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000003 ┆ CUST-0060 ┆ 2023-02-2 ┆ Europe    ┆ … ┆ 7.89      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000004 ┆ CUST-0065 ┆ 2023-12-2 ┆ Latin     ┆ … ┆ 17.06     ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000005 ┆ CUST-0036 ┆ 2023-05-2 ┆ Asia      ┆ … ┆ 7.26      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000006 ┆ CUST-0032 ┆ 2023-05-0 ┆ Europe    ┆ … ┆ 19.72     ┆ online  ┆ completed ┆ SPRING10  │
│            ┆           ┆ 9         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000007 ┆ CUST-0070 ┆ 2023-05-1 ┆ North     ┆ … ┆ 6.28      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000008 ┆ CUST-0175 ┆ 2023-08-2 ┆ North     ┆ … ┆ 7.79      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 1         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000009 ┆ CUST-0001 ┆ 2023-08-2 ┆ Asia      ┆ … ┆ 9.14      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000010 ┆ CUST-0057 ┆ 2023-06-2 ┆ Asia      ┆ … ┆ 2.7       ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 2         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 4. Show the **last 5 rows**.

In [4]:
orders.tail(5)

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000996 ┆ CUST-0132 ┆ 2023-07-0 ┆ North     ┆ … ┆ 20.78     ┆ online  ┆ cancelled ┆ null      │
│            ┆           ┆ 6         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000997 ┆ CUST-0190 ┆ 2023-04-1 ┆ Latin     ┆ … ┆ 9.13      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 8         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000998 ┆ CUST-0058 ┆ 2023-04-0 ┆ North     ┆ … ┆ 1.4       ┆ online  ┆ pending   ┆ SPRING10  │
│            ┆           ┆ 5         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000999 ┆ CUST-0051 ┆ 2023-01-2 ┆ Asia      ┆ … ┆ 3.11      ┆ online  ┆ returned  ┆ VIP       │
│            ┆           ┆ 6         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
│ ORD-001000 ┆ CUST-0147 ┆ 2023-08-3 ┆ Latin     ┆ … ┆ 8.87      ┆ partner ┆ completed ┆ null      │
│            ┆           ┆ 0         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 5. How many **rows and columns** does the dataset have?

In [5]:
orders.shape

(1000, 12)

### 6. What are the **column names**?

In [6]:
orders.columns

['order_id',
 'customer_id',
 'order_date',
 'region',
 'product_sku',
 'category',
 'product_name',
 'quantity',
 'unit_price',
 'channel',
 'status',
 'discount_code']

### 7. What is the **data type of every column**? Notice which type `order_date` got.

In [7]:
orders.schema

Schema([('order_id', String),
        ('customer_id', String),
        ('order_date', String),
        ('region', String),
        ('product_sku', String),
        ('category', String),
        ('product_name', String),
        ('quantity', Int64),
        ('unit_price', Float64),
        ('channel', String),
        ('status', String),
        ('discount_code', String)])

### 8. Get **summary statistics** for all columns in one call.

In [8]:
orders.describe()

shape: (9, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ statistic  ┆ order_id  ┆ customer_ ┆ order_dat ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ ---       ┆ id        ┆ e         ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆           ┆ str       ┆ str       ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ count      ┆ 1000      ┆ 1000      ┆ 1000      ┆ … ┆ 1000.0    ┆ 1000    ┆ 1000      ┆ 427       │
│ null_count ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0       ┆ 0         ┆ 573       │
│ mean       ┆ null      ┆ null      ┆ null      ┆ … ┆ 8.89282   ┆ null    ┆ null      ┆ null      │
│ std        ┆ null      ┆ null      ┆ null      ┆ … ┆ 6.682153  ┆ null    ┆ null      ┆ null      │
│ min        ┆ ORD-00000 ┆ CUST-0001 ┆ 2023-01-0 ┆ … ┆ 1.02      ┆ online  ┆ cancelled ┆ BULK      │
│            ┆ 1         ┆           ┆ 1         ┆   ┆           ┆         ┆           ┆           │
│ 25%        ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.29      ┆ null    ┆ null      ┆ null      │
│ 50%        ┆ null      ┆ null      ┆ null      ┆ … ┆ 7.31      ┆ null    ┆ null      ┆ null      │
│ 75%        ┆ null      ┆ null      ┆ null      ┆ … ┆ 11.79     ┆ null    ┆ null      ┆ null      │
│ max        ┆ ORD-00100 ┆ CUST-0200 ┆ 2023-12-3 ┆ … ┆ 25.98     ┆ store   ┆ returned  ┆ VIP       │
│            ┆ 0         ┆           ┆ 1         ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 9. Use **`glimpse()`** for a transposed, one-line-per-column overview (great for wide datasets).

In [9]:
orders.glimpse()

Rows: 1000
Columns: 12
$ order_id      <str> 'ORD-000001', 'ORD-000002', 'ORD-000003', 'ORD-000004', 'ORD-000005', 'ORD-000006', 'ORD-000007', 'ORD-000008', 'ORD-000009', 'ORD-000010'
$ customer_id   <str> 'CUST-0171', 'CUST-0049', 'CUST-0060', 'CUST-0065', 'CUST-0036', 'CUST-0032', 'CUST-0070', 'CUST-0175', 'CUST-0001', 'CUST-0057'
$ order_date    <str> '2023-10-25', '2023-12-02', '2023-02-27', '2023-12-26', '2023-05-24', '2023-05-09', '2023-05-10', '2023-08-21', '2023-08-29', '2023-06-22'
$ region        <str> 'Asia Pacific', 'North America', 'Europe', 'Latin America', 'Asia Pacific', 'Europe', 'North America', 'North America', 'Asia Pacific', 'Asia Pacific'
$ product_sku   <str> 'PB200', 'SH900', 'BK300', 'SH900', 'PT010', 'BK301', 'PT010', 'BK300', 'PT044', 'PB200'
$ category      <str> 'pens', 'shirts', 'books', 'shirts', 'posters', 'books', 'posters', 'books', 'posters', 'pens'
$ product_name  <str> 'Gel Pen 12-pack', 'Cotton T-Shirt', 'Paperback Book', 'Cotton T-Shirt', 'Motivational Poster', 'Cookbook', 'Motivational Poster', 'Paperback Book', 'World Map Poster', 'Gel Pen 12-pack'
$ quantity      <i64> 15, 5, 16, 37, 11, 35, 11, 8, 11, 13
$ unit_price    <f64> 2.7, 17.88, 7.89, 17.06, 7.26, 19.72, 6.28, 7.79, 9.14, 2.7
$ channel       <str> 'online', 'online', 'online', 'online', 'online', 'online', 'online', 'partner', 'online', 'online'
$ status        <str> 'completed', 'completed', 'completed', 'completed', 'completed', 'completed', 'completed', 'completed', 'completed', 'completed'
$ discount_code <str> 'SPRING10', 'BULK', 'BULK', 'BULK', None, 'SPRING10', None, None, None, None

### 10. Select **only the `product_name` column**.

In [10]:
orders.select("product_name")

shape: (1_000, 1)
┌─────────────────────┐
│ product_name        │
│ ---                 │
│ str                 │
╞═════════════════════╡
│ Gel Pen 12-pack     │
│ Cotton T-Shirt      │
│ Paperback Book      │
│ Cotton T-Shirt      │
│ Motivational Poster │
│ …                   │
│ Cookbook            │
│ World Map Poster    │
│ Sticker Sheet       │
│ Gel Pen 12-pack     │
│ Paperback Book      │
└─────────────────────┘

### 11. Select the columns `order_id`, `product_name`, `quantity`, `unit_price`.

In [11]:
orders.select("order_id", "product_name", "quantity", "unit_price")

shape: (1_000, 4)
┌────────────┬─────────────────────┬──────────┬────────────┐
│ order_id   ┆ product_name        ┆ quantity ┆ unit_price │
│ ---        ┆ ---                 ┆ ---      ┆ ---        │
│ str        ┆ str                 ┆ i64      ┆ f64        │
╞════════════╪═════════════════════╪══════════╪════════════╡
│ ORD-000001 ┆ Gel Pen 12-pack     ┆ 15       ┆ 2.7        │
│ ORD-000002 ┆ Cotton T-Shirt      ┆ 5        ┆ 17.88      │
│ ORD-000003 ┆ Paperback Book      ┆ 16       ┆ 7.89       │
│ ORD-000004 ┆ Cotton T-Shirt      ┆ 37       ┆ 17.06      │
│ ORD-000005 ┆ Motivational Poster ┆ 11       ┆ 7.26       │
│ …          ┆ …                   ┆ …        ┆ …          │
│ ORD-000996 ┆ Cookbook            ┆ 2        ┆ 20.78      │
│ ORD-000997 ┆ World Map Poster    ┆ 37       ┆ 9.13       │
│ ORD-000998 ┆ Sticker Sheet       ┆ 16       ┆ 1.4        │
│ ORD-000999 ┆ Gel Pen 12-pack     ┆ -5       ┆ 3.11       │
│ ORD-001000 ┆ Paperback Book      ┆ 34       ┆ 8.87       │
└────────────┴─────────────────────┴──────────┴────────────┘

### 12. How many **distinct products** (`product_sku`) appear in the data?

In [12]:
orders["product_sku"].n_unique()

12

### 13. List the **distinct categories**.

In [13]:
orders["category"].unique().sort()

shape: (7,)
Series: 'category' [str]
[
	"books"
	"mugs"
	"notebooks"
	"pens"
	"posters"
	"shirts"
	"stickers"
]

### 14. How many orders are there **per `status`**? (use `value_counts`)

In [14]:
orders["status"].value_counts(sort=True)

shape: (4, 2)
┌───────────┬───────┐
│ status    ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ completed ┆ 820   │
│ pending   ┆ 83    │
│ cancelled ┆ 54    │
│ returned  ┆ 43    │
└───────────┴───────┘

### 15. Which **category** has the most orders?

In [15]:
orders["category"].value_counts(sort=True).head(1)

shape: (1, 2)
┌──────────┬───────┐
│ category ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ posters  ┆ 180   │
└──────────┴───────┘

### 16. What are the **minimum and maximum `quantity`**? (remember: returns are negative)

In [16]:
orders["quantity"].min(), orders["quantity"].max()

(-5, 39)

### 17. What is the **average `unit_price`**, rounded to 2 decimals?

In [17]:
orders.select(pl.col("unit_price").mean().round(2))

shape: (1, 1)
┌────────────┐
│ unit_price │
│ ---        │
│ f64        │
╞════════════╡
│ 8.89       │
└────────────┘

### 18. How many **null (missing) values** does each column have? Which column is dirty?

In [18]:
orders.null_count()

shape: (1, 12)
┌──────────┬─────────────┬────────────┬────────┬───┬────────────┬─────────┬────────┬───────────────┐
│ order_id ┆ customer_id ┆ order_date ┆ region ┆ … ┆ unit_price ┆ channel ┆ status ┆ discount_code │
│ ---      ┆ ---         ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---     ┆ ---    ┆ ---           │
│ u32      ┆ u32         ┆ u32        ┆ u32    ┆   ┆ u32        ┆ u32     ┆ u32    ┆ u32           │
╞══════════╪═════════════╪════════════╪════════╪═══╪════════════╪═════════╪════════╪═══════════════╡
│ 0        ┆ 0           ┆ 0          ┆ 0      ┆ … ┆ 0          ┆ 0       ┆ 0      ┆ 573           │
└──────────┴─────────────┴────────────┴────────┴───┴────────────┴─────────┴────────┴───────────────┘

### 19. Take a **random sample of 5 rows** (use `seed=0` so it is reproducible).

In [19]:
orders.sample(5, seed=0)

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000446 ┆ CUST-0124 ┆ 2023-06-2 ┆ Europe    ┆ … ┆ 10.44     ┆ online  ┆ completed ┆ VIP       │
│            ┆           ┆ 4         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000438 ┆ CUST-0061 ┆ 2023-08-0 ┆ North     ┆ … ┆ 6.65      ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 7         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000978 ┆ CUST-0028 ┆ 2023-04-0 ┆ Europe    ┆ … ┆ 14.47     ┆ online  ┆ cancelled ┆ BULK      │
│            ┆           ┆ 7         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000462 ┆ CUST-0060 ┆ 2023-08-2 ┆ Europe    ┆ … ┆ 1.62      ┆ online  ┆ pending   ┆ null      │
│            ┆           ┆ 4         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000898 ┆ CUST-0099 ┆ 2023-10-0 ┆ Asia      ┆ … ┆ 6.57      ┆ online  ┆ completed ┆ BULK      │
│            ┆           ┆ 9         ┆ Pacific   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 20. What is the **estimated in-memory size** of the DataFrame, in MB?

In [20]:
orders.estimated_size("mb")

0.09344100952148438

### 21. Show the **5 largest orders by `quantity`** (highest quantity first).

In [21]:
orders.sort("quantity", descending=True).head(5)

shape: (5, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ order_id   ┆ customer_ ┆ order_dat ┆ region    ┆ … ┆ unit_pric ┆ channel ┆ status    ┆ discount_ │
│ ---        ┆ id        ┆ e         ┆ ---       ┆   ┆ e         ┆ ---     ┆ ---       ┆ code      │
│ str        ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│            ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆         ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ORD-000022 ┆ CUST-0199 ┆ 2023-10-1 ┆ Europe    ┆ … ┆ 16.22     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 5         ┆           ┆   ┆           ┆         ┆           ┆           │
│ ORD-000103 ┆ CUST-0046 ┆ 2023-04-2 ┆ Latin     ┆ … ┆ 20.89     ┆ store   ┆ completed ┆ null      │
│            ┆           ┆ 4         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000121 ┆ CUST-0173 ┆ 2023-10-2 ┆ North     ┆ … ┆ 10.03     ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 9         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000124 ┆ CUST-0031 ┆ 2023-03-0 ┆ North     ┆ … ┆ 6.05      ┆ online  ┆ completed ┆ null      │
│            ┆           ┆ 3         ┆ America   ┆   ┆           ┆         ┆           ┆           │
│ ORD-000201 ┆ CUST-0061 ┆ 2023-06-1 ┆ North     ┆ … ┆ 6.82      ┆ store   ┆ completed ┆ VIP       │
│            ┆           ┆ 2         ┆ America   ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

### 22. Select rows **10 through 14** (a 5-row slice) using `slice`. Add a row index first with `with_row_index()` so you can see the 0-based positions in the output.

In [22]:
orders.with_row_index().slice(10, 5)

shape: (5, 13)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬───────────┬────────────┐
│ index ┆ order_id   ┆ customer_i ┆ order_date ┆ … ┆ unit_price ┆ channel ┆ status    ┆ discount_c │
│ ---   ┆ ---        ┆ d          ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---       ┆ ode        │
│ u32   ┆ str        ┆ ---        ┆ str        ┆   ┆ f64        ┆ str     ┆ str       ┆ ---        │
│       ┆            ┆ str        ┆            ┆   ┆            ┆         ┆           ┆ str        │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪═══════════╪════════════╡
│ 10    ┆ ORD-000011 ┆ CUST-0013  ┆ 2023-01-26 ┆ … ┆ 17.42      ┆ online  ┆ completed ┆ null       │
│ 11    ┆ ORD-000012 ┆ CUST-0113  ┆ 2023-12-27 ┆ … ┆ 2.82       ┆ online  ┆ completed ┆ BULK       │
│ 12    ┆ ORD-000013 ┆ CUST-0051  ┆ 2023-03-23 ┆ … ┆ 1.44       ┆ partner ┆ completed ┆ null       │
│ 13    ┆ ORD-000014 ┆ CUST-0159  ┆ 2023-02-04 ┆ … ┆ 21.08      ┆ partner ┆ completed ┆ null       │
│ 14    ┆ ORD-000015 ┆ CUST-0118  ┆ 2023-08-07 ┆ … ┆ 6.94       ┆ online  ┆ completed ┆ SPRING10   │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴───────────┴────────────┘